[workspace]
members = [
    "halo2",
    "halo2_gadgets",
    "halo2_proofs",
]



[patch."https://github.com/privacy-scaling-explorations/poseidon.git"]
poseidon = { git = "https://github.com/scroll-tech/poseidon.git", branch = "halo2-ecc-snark-verifier-0220" }